language: generic
sudo: required
services:
  -docker
before_install:
  - docker build -t kurotyan514/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true kurotyan514/docker-react yarn test
