language: generic
sudo: required
services:
  -docker
before_install:
  - docker build -t kurotyan514/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true kurotyan514/docker-react yarn test
deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-northeast-1-825716277951
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
