version: '3'
services: 
  web:
    build:
      # all the files and folders for this image to be pulled from
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - '3000:3000'
    volumes: 
      # Do not try to map a folder up against app node modules inside the container.
      - '/app/node_modules'
      - '.:/app'
    # fix the error that is raise exited with code 0 when
    # run docker-compose up
    stdin_open: true
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - '/app/node_modules'
      - '.:/app'
    command: ["yarn", "test"]